export const ledeText =
  "<img class='float-image' src='assets/characters/achey-hollow/zach.svg' /><p>There's a world that's difficult to grasp. Let alone explain.</p> <p>Some have tried to explain it with science. Others say it's a world of magic. Others want to say it's some kind of technology run amok.</p><p>The truth is, it's somewhere in between.</p> <p>The glimmer in the corner of your eye? The shadow that just inexplicably moved? That strange sound with no identifiable source?</p> <p>That's the world of which I speak. It's not here or there. It's somewhere in between. Or Betwixt.</p><p>Labels? No way.</p><p>Moral lessons? Not here.</p><p>Disabled kids defined by who they are, not what they have.</p> <p>Boys who like boys. Girls who like girls. They and Them aren't pronouns - they're identities.</p> <p>Every culture and every experience is seen. Every character is represented without apology or explanation.</p> <p>There's a neighborhood where two neighbors have pined for each other as long as they can remember. They've always been close. Always sneaking glances when the other isn't looking. Some would say they're perfect for one another. But when Death comes knocking, Time doesn't just slow down, he has to stop.</p> <p>In a neighborhood across town, twin brothers are always trying to win the heart of the most Faithful girl in town. She's very popular because children are taught to love her from an early age. One twin is trying to impress her by conquering the world. The other, just wants everyone to hold hands and get along. As for the girl, the low hum of her meditation is heavenly. Much more than War. Much more than Peace.</p> <p>Then there's a neighborhood near the center of town. A 10 and 12 year old are arguing about how to decorate for the afterparty. One wants gold everything. But no music. Everyone has to be able to hear a feather drop. The other wants a raucous free for all. No matter how wild the party gets, all is forgiven by sunset. When these two get together, you better believe they'll be Hel to pay.</p> <p>Down one street, the kids don't play games. They LIVE them. The map is always on the table. Every quest is real. Every roll of the die has consequences. Will the one fail and the twenty make a hit? No one knows till the Master makes the call.</p> <p>What about the two residents sitting at the playground? They pass the time discussing what means more - Love or Desire. The heart or the...well, you know. Does one make the world go round? Does one want to just burn it all down? Or will they just seesaw and swing?</p> <p>At the center of it all, there's the sweet little old lady who's the part time cook at the diner. Everyone adores her despite her penchant for forgetting orders and… “Where did this ball of yarn come from? I could have sworn you ordered spaghetti, dearie. What was I saying again?”</p><p>You got neighbors? Now meet ours…</p>";
export const aboutText =
  '<p>Residents are inclusive, dignified, and defined by who they are — not what they have. Worry is a kid, not a symptom. Big Feeling is not a problem to solve. They are just neighbors.</p>';
export const makeText =
  '<p>Slowly, by hand, in cream and teal. Nothing here is generated; nothing is glossy. The wobble in the letters and the warmth in the page are the point.</p>';
export const dontText =
  "<p>We don't diagnose. We don't gamify. We don't push notifications. We don't believe a kid is a metric.</p>";
export const hopeText =
  '<p> That a kid meets a neighbor. That a grown-up remembers one. That for a minute the world is just a little more porch and a little less feed. </p>';
